# name: Flutter Web CI/CD

# on:
#   push:
#     branches:
#       # - master
#       - dev
#       - test

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Set up Flutter
#       uses: subosito/flutter-action@v2
#       with:
#         flutter-version: '3.0.2'

#     - name: Check out code
#       uses: actions/checkout@v2

#     - name: Install dependencies
#       run: flutter pub get


#     - name: Build web
#       run: flutter build web

  

 
  
name: Flutter Action

on:
  push:
    branches:
      # - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          java-version: '12.x'

      - uses: subosito/flutter-action@v2
        with:
         flutter-version: '3.0.2'

      - run: flutter pub get
      - run: flutter build apk

      - uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk