name: Flutter Web CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: stable

    - name: Check out code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: flutter pub get

    - name: Build and test
      run: flutter test

    - name: Build web
      run: flutter build web
